Module 2 - numpy

1a. Create a csv file from the list below

In [33]:
table = [ "123 lucy psychology 3.25".split(), "345 linus undeclared 2.89".split(), "567 schroeder music 3.93".split() ] 

In [36]:
import csv 
with open("ex2.csv", 'w', newline = '') as f:
    writer = csv.writer(f)
    for row in table:
        writer.writerow(row)

1b. Print data from the CSV file to show that it was created successfully

In [12]:
with open("ex2.csv", 'r', newline = '') as f:
    reader = csv.reader(f)
    for alist in reader:
        print(alist)


['123', 'lucy', 'psychology', '3.25']
['345', 'linus', 'undeclared', '2.89']
['567', 'schroeder', 'music', '3.93']
123 lucy psychology 3.25
345 linus undeclared 2.89
567 schroeder music 3.93


In [38]:
with open("ex2.csv", 'r', newline = '') as f:
    for line in f:
        print(line.rstrip())

123,lucy,psychology,3.25
345,linus,undeclared,2.89
567,schroeder,music,3.93


In [39]:
# its a generator!
with open("ex2.csv") as f:
    print(next(f))

123,lucy,psychology,3.25



In [41]:
import numpy as np
arr = np.loadtxt("ex2.csv", delimiter = ',', dtype=str)
arr

array([['123', 'lucy', 'psychology', '3.25'],
       ['345', 'linus', 'undeclared', '2.89'],
       ['567', 'schroeder', 'music', '3.93']], dtype='<U10')

2a. Given the following code, predict and then show the data type and shape of the array

In [13]:
import numpy as np

L = [1,3,5,7,9]
arr = np.array(([1,2,3,4,5], L, [10,20,30.5,52.8,12], list(range(5))))


In [42]:
# will be an ndarray of 4 lists (python objects)
# shape: (4,) = ndarray of 4 objects (different data types)
arr?
arr.shape
print(arr.dtype)

<U10


Type:        ndarray
String form:
[['123' 'lucy' 'psychology' '3.25']
 ['345' 'linus' 'undeclared' '2.89']
 ['567' 'schroeder' 'music' '3.93']]
Length:      3
File:        ~/opt/anaconda3/lib/python3.9/site-packages/numpy/__init__.py
Docstring:  
ndarray(shape, dtype=float, buffer=None, offset=0,
        strides=None, order=None)

An array object represents a multidimensional, homogeneous array
of fixed-size items.  An associated data-type object describes the
format of each element in the array (its byte-order, how many bytes it
occupies in memory, whether it is an integer, a floating point number,
or something else, etc.)

Arrays should be constructed using `array`, `zeros` or `empty` (refer
to the See Also section below).  The parameters given here refer to
a low-level method (`ndarray(...)`) for instantiating an array.

For more information, refer to the `numpy` module and examine the
methods and attributes of an array.

Parameters
----------
(for the __new__ method; see Notes belo

2b. Change arr to a 10 row by 2 col array, and print it out

In [15]:
# first use np.hstack to stack the rows horizontally
stacked_arr = np.hstack(arr)
stacked_arr.shape

(20,)

In [32]:
# next, use np.reshape to reshape the array
reshaped_arr = stacked_arr.reshape(10, 2)
reshaped_arr.shape

(10, 2)

In [17]:
# print the array
for row in reshaped_arr:
    print(*row, sep='\t')

1.0	2.0
3.0	4.0
5.0	1.0
3.0	5.0
7.0	9.0
10.0	20.0
30.5	52.8
12.0	0.0
1.0	2.0
3.0	4.0


3. Given the following array. Print all values that are above 10

In [18]:
arr = np.array([[3,9,10,2],[23,18,2,4],[7,4,22,5]])


In [19]:
# prints all values above 10
# arr > 10 returns a boolean array
# arr[arr > 10] returns the values of arr where arr > 10 is True
# the * unpacks the array into a list of values
print(*arr[arr > 10], sep='\n')

23
18
22


4a. For arr below, change all values in the 2nd and 3rd rows  to 0 and print the first 3 rows. Then print the array.

In [46]:
arr = np.array([[3,9,10],[2,27,0],[23,18,2],[7,4,5]])
arr.shape
print(*arr, sep='\n')

# alt
for row in arr:
    print(*row, sep='\t')

[ 3  9 10]
[ 2 27  0]
[23 18  2]
[7 4 5]
3	9	10
2	27	0
23	18	2
7	4	5


In [47]:
print(*arr[1:3], sep = '\n')

[ 2 27  0]
[23 18  2]


In [22]:
print("change 2nd & 3rd rows to 0s")
arr[1:3] = 0
print(*arr, sep='\n')
print("print first 3 rows")
print(*arr[:3], sep='\n')

change 2nd & 3rd rows to 0s
[ 3  9 10]
[0 0 0]
[0 0 0]
[7 4 5]
print first 3 rows
[ 3  9 10]
[0 0 0]
[0 0 0]


4b. Make a copy of arr and call it arr2. Increment every element in the last column of arr2 by 10. Print arr and arr2.

In [48]:
# create a copy of arr
arr2 = arr.copy()
# increment every element in last col of arr2 by 10
# syntax: arr2[:,2] means all rows, 3rd column
arr2[:,-1] += 10
print("arr")
print(*arr, sep='\n')
print("arr2")
print(*arr2, sep='\n')



arr
[ 3  9 10]
[ 2 27  0]
[23 18  2]
[7 4 5]
arr2
[ 3  9 20]
[ 2 27 10]
[23 18 12]
[ 7  4 15]


4c. Write code to print whether the last column of arr and arr2 are equal

In [49]:
print(np.array_equal(arr[:,-1], arr2[:,-1]))

False


5. What do these produce?

In [25]:
arr =  np.random.random(10)             # 1D array of 10 random floats            
print(arr)

# np.random.randint(low, high, size) returns an array of random ints in [low, high)
arr = np.random.randint(1, 10, size=15) # 1D array of 15 random ints in [1,10)  
print(arr)                              

# np.linspace(low, high, num) returns an array of num floats in [low, high]
arr = np.linspace(-50,40,10)            # 1D array of 10 floats in [-50,40]  
print(arr)

# np.arange(low, high, step) returns an array of ints in [low, high) with step
arr = np.arange(1,10,2)                 # 1D array of ints in [1,10) with step 2  
print(arr)

[0.3501786  0.55860883 0.76118406 0.36490679 0.26079641 0.98957647
 0.63185655 0.32967149 0.92016602 0.57973457]
[9 8 9 1 4 5 7 5 3 4 8 5 1 6 7]
[-50. -40. -30. -20. -10.   0.  10.  20.  30.  40.]
[1 3 5 7 9]


6. Create an array of 10 random integers between 100 and 500, and calculate their mean and standard deviation.  Are the values close together or far apart?

In [51]:
# np.random.randint(low, high, size) returns an array of random ints in [low, high)
# arr or 10 random ints in [100, 500]
rand_arr = np.random.randint(100, 501, size=10)

print(np.mean(rand_arr))
print(np.std(rand_arr))

282.2
102.87643073124184


7. Sort the array below, and then show the indices that would sort the array

In [54]:
arr = np.array([[5,2,1,14,5], [7,32,19,4,5], [10,20,3,5,12]])

# sort the array, then show indeces that would sort the array
print("unsorted array")
print(arr)

# sort the array
print("sorted array, w axis = 0")
sorted_arr = np.sort(arr, axis=0)
print(sorted_arr)

print("sorted array, w axis = 1")
sorted_arr = np.sort(arr, axis=1)
print(sorted_arr)

# argsort returns the indeces that would sort the array
print("argsort")
print(np.argsort(arr))

unsorted array
[[ 5  2  1 14  5]
 [ 7 32 19  4  5]
 [10 20  3  5 12]]
sorted array, w axis = 0
[[ 5  2  1  4  5]
 [ 7 20  3  5  5]
 [10 32 19 14 12]]
sorted array, w axis = 1
[[ 1  2  5  5 14]
 [ 4  5  7 19 32]
 [ 3  5 10 12 20]]
argsort
[[2 1 0 4 3]
 [3 4 0 2 1]
 [2 3 0 4 1]]


In [59]:
arr1 = np.array([9, 3, 2, 5])
arr2 = np.array([1, 2, 3, 4])

ind = np.argsort(arr)
ind

array([2, 1, 3, 0])

In [60]:
print(arr1[ind])
print(arr2[ind])

[2 3 5 9]
[3 2 4 1]
